Ireland - Richard Yun
richardyun/css_flag_challenges pull request #3
Opened 2019-07-06 22:00 UTC by richardyun

![ireland](https://user-images.githubusercontent.com/45304110/60761517-d1178580-9ffe-11e9-9863-300dbf757cf6.jpg)

2019-07-06 22:13 UTC, dpaschal-lf commented
please make successive screen shots focused on the area being reviewed

2019-07-06 22:13 UTC, dpaschal-lf commented on flags.css
> +    height: 200px;
change the flag container so you don't have to keep doing this for every id.

2019-07-06 22:16 UTC, dpaschal-lf commented on flags.css
> +    display: inline-block;
there's no point in making it inline-block.  flex children will change size

2019-07-06 22:16 UTC, dpaschal-lf commented on flags.html
> +            <div class="leftSegment green"></div>
again... why with the color classes that you aren't using?

2019-07-06 22:16 UTC, dpaschal-lf requested changes
similar problems to before, and also a needless display property

2019-07-07 01:58 UTC, richardyun commented
![ireland](https://user-images.githubusercontent.com/45304110/60763004-0bdde580-a020-11e9-94ad-af00960e8379.jpg)

2019-07-07 02:00 UTC, dpaschal-lf commented on flags.css
> +#ireland>.leftSegment, #ireland>.middleSegment, #ireland>.rightSegment {
could have also said 
```
#ireland > *
```

2019-07-07 02:00 UTC, dpaschal-lf approved these changes

2019-07-08 02:13 UTC, merged